# CONFIG FILE FOR AN LID EXPERIMENT
model_save_dir: '/saved_model'
seed: 1337
source_language_set: 
    languages : 'fr de nl'
    dataset : "/corpora/voxlingua"
    train_split : "train"
    validation_split : "validation"
experiment_name: 'cnn_as_encoder'
#
input_signal_params:
    max_duration : 10.0 #seconds
    max_num_frames: 454
    num_frames: 300
    sampling_rate: 16000
    sample_segment: True
    start_index: 0
    end_index: 13
#
encoder_arch:
    encoder_model: ConvEncoder
    spectral_dim: 512
    frame_dropout: True # either frame_dropout or feature_dropout can be True
    feature_dropout: False
    signal_dropout_prob: 0.0
    num_channels:
       - 128
       - 256
       - 512
    filter_sizes:
       - 8
       - 16
       - 24
    stride_steps:
       - 1
       - 1
       - 1
    pooling_type: 'max'
#
classifier_arch:
    num_classes: 3
    input_dim: 512
    hidden_dim: 512
    num_layers: 3
    unit_dropout: False
    dropout_prob: 0.0
#
training_hyperparams:
    learning_rate: 0.001
    batch_size: 256
    num_epochs: 100
    early_stopping_criteria: 50
cuda: True
catch_keyboard_interrupt: True
reload_from_files: False
expand_filepaths_to_save_dir: True
